export const GET_PAY_METHODS_REQUEST = "GET_PAY_METHODS_REQUEST";
export const GET_PAY_METHODS_SUCCESS = "GET_PAY_METHODS_SUCCESS";
export const GET_PAY_METHODS_ERROR  = "GET_PAY_METHODS_ERROR";

export const CALCULATE_PAY_METHODS_REQUEST = "CALCULATE_PAY_METHODS_REQUEST";
export const CALCULATE_PAY_METHODS_SUCCESS = "CALCULATE_PAY_METHODS_SUCCESS";
export const CALCULATE_PAY_METHODS_ERROR  = "CALCULATE_PAY_METHODS_ERROR";

export const SAVE_DETAILS_EXCHANGE  = "SAVE_DETAILS_EXCHANGE";
export const CLEAR_DATA_EXCHANGE  = "CLEAR_DETAILS_EXCHANGE";

export const CONFIRM_EXCHANGE_REQUEST = "CONFIRM_EXCHANGE_REQUEST";
export const CONFIRM_EXCHANGE_SUCCESS = "CONFIRM_EXCHANGE_SUCCESS";
export const CONFIRM_EXCHANGE_ERROR  = "CONFIRM_EXCHANGE_ERROR";

export const CLEAR_CONFIRM_DATA = "CLEAR_CONFIRM_DATA";
