export const GET_ALL_MOVIES_REQUEST = "GET_ALL_MOVIES_REQUEST";
export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_ERROR  = "GET_ALL_MOVIES_ERROR";

export const SEARCH_MOVIE_REQUEST = "SEARCH_MOVIE_REQUEST";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const SEARCH_MOVIE_ERROR = "SEARCH_MOVIE_ERROR";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_ERROR = "DELETE_MOVIE_ERROR";

export const ADD_MOVIE_REQUEST = "ADD_MOVIE_REQUEST";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";

export const UPLOAD_MOVIE_REQUEST = "UPLOAD_MOVIE_REQUEST";
export const UPLOAD_MOVIE_SUCCESS = "UPLOAD_MOVIE_SUCCESS";
export const UPLOAD_MOVIE_ERROR = "UPLOAD_MOVIE_ERROR";

export const GET_SINGLE_MOVIE_REQUEST = "GET_SINGLE_MOVIE_REQUEST";
export const GET_SINGLE_MOVIE_SUCCESS = "GET_SINGLE_MOVIE_SUCCESS";
export const GET_SINGLE_MOVIE_ERROR = "GET_SINGLE_MOVIE_ERROR";

